/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "fileops.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

file_chunk *
fileopen_1(file_chunk_info *argp, CLIENT *clnt)
{
	static file_chunk clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, FILEOPEN,
		(xdrproc_t) xdr_file_chunk_info, (caddr_t) argp,
		(xdrproc_t) xdr_file_chunk, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

file_chunk *
fileclose_1(file_flush_data *argp, CLIENT *clnt)
{
	static file_chunk clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, FILECLOSE,
		(xdrproc_t) xdr_file_flush_data, (caddr_t) argp,
		(xdrproc_t) xdr_file_chunk, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

file_chunk *
fileread_1(file_chunk_info *argp, CLIENT *clnt)
{
	static file_chunk clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, FILEREAD,
		(xdrproc_t) xdr_file_chunk_info, (caddr_t) argp,
		(xdrproc_t) xdr_file_chunk, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

file_chunk *
filecreate_1(file_chunk_info *argp, CLIENT *clnt)
{
	static file_chunk clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, FILECREATE,
		(xdrproc_t) xdr_file_chunk_info, (caddr_t) argp,
		(xdrproc_t) xdr_file_chunk, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
