/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "fileops.h"

bool_t
xdr_errors (XDR *xdrs, errors *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_file_chunk (XDR *xdrs, file_chunk *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->last))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_errors (xdrs, &objp->err))
		 return FALSE;
	 if (!xdr_opaque (xdrs, objp->data, FILE_BLOCK))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_file_chunk_info (XDR *xdrs, file_chunk_info *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->filePath, 255))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->offset))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_file_flush_data (XDR *xdrs, file_flush_data *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_opaque (xdrs, objp->data, FILE_BLOCK))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->filePath, 255))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->size))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->last))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->offset))
		 return FALSE;
	return TRUE;
}
