/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "fileops.h"
#include<stdio.h>
#include<stdlib.h>
#include<string.h>

file_chunk *
fileopen_1_svc(file_chunk_info *argp, struct svc_req *rqstp)
{
	static file_chunk  result;

	/*
	 * insert server code here
	 */
	char* filePath = argp->filePath;
//	printf("%s\n", filePath);
	int offset = argp->offset;
	FILE *fp;
	if((fp = fopen(filePath, "rb"))==NULL){
		perror("Cant open file\n");
		result.last = 1;
		fclose(fp);
		return &result;
	}	
	
	fseek(fp, offset, SEEK_SET);
	result.size = fread(result.data, 1, FILE_BLOCK, fp);
	result.last = feof(fp);
	fclose(fp);
	return &result;
}

file_chunk *
fileclose_1_svc(file_flush_data *argp, struct svc_req *rqstp)
{
	static file_chunk  result;

	/*
	 * insert server code here
	 */
	int offset = argp->offset;
	char *filePath = argp->filePath;
	
	FILE *fp;
//	printf("%s\n", filePath);
	if((fp = fopen(filePath, "ab"))==NULL){
		result.size = 0;
		result.err = 1;
		result.err = 0;
		return &result;
	}	
	fseek(fp, offset, SEEK_SET);
	fwrite(argp->data, 1, argp->size, fp);
	if(argp->last)fflush(fp);
	fclose(fp);
	printf("received  %s\n", argp->data);
	result.size = argp->size;
	result.last = argp->last;
	result.err= 1;		
	return &result;
}

file_chunk *
fileread_1_svc(file_chunk_info *argp, struct svc_req *rqstp)
{
	static file_chunk  result;

	/*
	 * insert server code here
	 */

	return &result;
}

file_chunk *
filecreate_1_svc(file_chunk_info *argp, struct svc_req *rqstp)
{
	static file_chunk  result;

	/*
	 * insert server code here
	 */

	return &result;
}
